#!/usr/bin/env python3
"""Regenerate site/data.js from REAL runs of the two demos.

Nothing on the website is hand-written output: the terminal transcripts, the task graph and the contract blast
radii are captured from `examples/demo.sh` and `examples/demo-two-machines.sh`. Run `make site-data` after
changing behaviour, then commit site/data.js.
"""
import json, os, re, subprocess, sys, tempfile

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
env = dict(os.environ, NO_COLOR="1", WBI_NO_GH="1")
ANSI = re.compile(r"\x1b\[[0-9;]*m")

def run_demo(script, name):
    d = os.path.join(tempfile.mkdtemp(), name)
    out = subprocess.run(["bash", os.path.join(ROOT, "examples", script)], env=dict(env, DEMO_DIR=d), stdout=subprocess.PIPE, stderr=subprocess.STDOUT, text=True, check=True).stdout
    return d, ANSI.sub("", out)

def steps(out):
    """split demo output into {step number: text}"""
    parts = re.split(r"^▶ (\d+)\. .*$", out, flags=re.M)
    return {int(parts[i]): parts[i + 1].strip("\n") for i in range(1, len(parts) - 1, 2)}

def between(text, start, end=None):
    i = text.index(start)
    j = text.index(end, i) if end else len(text)
    return text[i:j].rstrip()

solo_dir, solo_out = run_demo("demo.sh", "healthai")
team_dir, team_out = run_demo("demo-two-machines.sh", "team")
S, T = steps(solo_out), steps(team_out)
wbi = os.path.join(ROOT, "bin", "wbi")

def sh(cwd, *args):
    return subprocess.run([wbi, *args], cwd=cwd, env=dict(env, WBI_NO_SYNC="1"), capture_output=True, text=True).stdout

graph = json.loads(sh(solo_dir, "dashboard", "--json"))
# a self-contained dashboard of the same real state, for the site's live demo
sh(solo_dir, "dashboard", "--out", os.path.join(ROOT, "site", "demo-dashboard.html"))
pr_body = sh(solo_dir, "pr", "TASK-007", "--dry-run")
gate = subprocess.run([wbi, "check", "--base", "main", "--head", "wbi/TASK-010"], cwd=solo_dir, env=dict(env, WBI_NO_SYNC="1"), stdout=subprocess.PIPE, stderr=subprocess.STDOUT, text=True).stdout
keep = ["id", "title", "layer", "display", "dependsOn", "provides", "consumes", "impact", "agent", "allowedPaths", "goal"]
tasks = [{k: t.get(k) for k in keep} for t in graph["tasks"]]
contracts = [{"name": c["name"], "version": c["version"], "providedBy": c["providedBy"], "kind": c["kind"], "public": c["public"], "shape": c["shape"]} for c in graph["contracts"]]

data = {
    "generated": "from examples/demo.sh and examples/demo-two-machines.sh",
    "tasks": tasks,
    "contracts": contracts,
    "blast": graph["blast"],
    "t": {
        "blame": between(S[12], "$ wbi blame", "Why does"),
        "why": between(S[12], "Why does", "DRIFT REPORT"),
        "drift": between(S[12], "DRIFT REPORT", "WAVE 1"),
        "blast": between(S[10], "BLAST RADIUS", "Gemini's inbox"),
        "inbox": between(S[10], "Gemini's inbox:", "WHO BROKE IT?").replace("Gemini's inbox:\n", ""),
        "status": between(S[10], "WHO BROKE IT?"),
        "intents": between(S[7], "Gemini (TASK-003)", None).split("\n", 1)[1].strip(),
        "blocked": S[5],
        "judge": between(S[11], "TASK-010 HANDOFF"),
        "handoff": between(S[9], "TASK-007 HANDOFF"),
        "pr": pr_body.strip(),
        "gate": gate.strip(),
        "plan": between(S[2], "EXECUTION PLAN", "✓ plan approved"),
        "race": between(T[5], "each machine believes", None).replace("\x1b", ""),
        "teaminbox": between(T[8], "BillingStatus changed", "BLAST") if "BLAST" in T[8] else between(T[8], "BillingStatus changed", "TASK-013"),
        "teamstatus": T[4],
    },
}
out = os.path.join(ROOT, "site", "data.js")
os.makedirs(os.path.dirname(out), exist_ok=True)
with open(out, "w") as f:
    f.write("// GENERATED by scripts/site-data.py from real demo runs. Do not edit by hand.\nwindow.WBI_DEMO = ")
    json.dump(data, f, indent=1, ensure_ascii=False)
    f.write(";\n")
print("wrote", out, "-", len(tasks), "tasks,", len(contracts), "contracts")
for k, v in data["t"].items():
    print(f"  {k:10s} {len(v.splitlines()):3d} lines")
